theme = 'hugo-theme-relearn'
baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'API Management with Kong Konnect - Serverless'
[module]
  [[module.imports]]
    path = 'github.com/McShelby/hugo-theme-relearn'
[params]
  themeVariant = "blue"
