deploymentMode: SingleBinary

singleBinary:
  replicas: 1
  persistence:
    enabled: false
  canary:
    enabled: false
    args:
      - -log-output=false
  extraVolumeMounts:
    - name: loki-storage
      mountPath: /var/loki
  extraVolumes:
    - name: loki-storage
      emptyDir: {}
  # service:
  #   type: LoadBalancer
  #   port: 3100
  #   targetPort: 3100
  #   name: loki

loki:
  commonConfig:
    replication_factor: 1
  image:
    tag: 3.5.3
  auth_enabled: false
  memberlist:
    join_members: []  # Empty list - no initial members to join
  storage:
    type: filesystem
    filesystem:
      chunks_directory: /var/loki/chunks
      rules_directory: /var/loki/rules

  schemaConfig:
    configs:
      - from: "2024-04-01"
        store: tsdb
        object_store: filesystem
        schema: v13
        index:
          prefix: loki_index_
          period: 24h

  limits_config:
    allow_structured_metadata: true
    volume_enabled: true

  ruler:
    enable_api: true

  pattern_ingester:
    enabled: true

chunksCache:
  enabled: false

resultsCache:
  enabled: false

indexGateway:
  enabled: false

minio:
  enabled: false

gateway:
  enabled: false

backend:
  replicas: 0
read:
  replicas: 0
write:
  replicas: 0
ingester:
  replicas: 0
querier:
  replicas: 0
queryFrontend:
  replicas: 0
queryScheduler:
  replicas: 0
distributor:
  replicas: 0
compactor:
  replicas: 0
bloomCompactor:
  replicas: 0
bloomGateway:
  replicas: 0